package Bai1;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;

public class SinhVien {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void sinhVien() {
        driver.get("https://demoqa.com/automation-practice-form");
        driver.manage().window().setSize(new Dimension(1440, 823));
        driver.findElement(By.id("firstName")).click();
        driver.findElement(By.id("firstName")).sendKeys("nhu");
        driver.findElement(By.id("lastName")).sendKeys("quynh");
        driver.findElement(By.id("userEmail")).sendKeys("nhu@gmail.com");
        driver.findElement(By.cssSelector(".custom-radio:nth-child(2) > .custom-control-label")).click();
        driver.findElement(By.id("userNumber")).click();
        driver.findElement(By.id("userNumber")).sendKeys("0982730329");
        driver.findElement(By.id("dateOfBirthInput")).click();
        driver.findElement(By.id("dateOfBirthInput")).click();
        driver.findElement(By.id("dateOfBirthInput")).click();
        driver.findElement(By.id("dateOfBirthInput")).sendKeys("19 Oct 2023");
        driver.findElement(By.cssSelector(".react-datepicker__month-select")).click();
        {
            WebElement dropdown = driver.findElement(By.cssSelector(".react-datepicker__month-select"));
            dropdown.findElement(By.xpath("//option[. = 'November']")).click();
        }
        driver.findElement(By.id("dateOfBirthInput")).click();
        driver.findElement(By.id("dateOfBirthInput")).sendKeys("19 Oct 1996");
        driver.findElement(By.cssSelector(".subjects-auto-complete__value-container")).click();
        driver.findElement(By.id("react-select-2-option-0")).click();
        driver.findElement(By.id("userForm")).click();
        {
            WebElement element = driver.findElement(By.id("userForm"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.cssSelector("#hobbiesWrapper > .col-md-9")).click();
        driver.findElement(By.cssSelector(".custom-checkbox:nth-child(3) > .custom-control-label")).click();
        driver.findElement(By.id("uploadPicture")).click();
        driver.findElement(By.id("uploadPicture")).sendKeys("C:\\fakepath\\Screen Shot 2023-10-09 at 15.52.33.png");
        driver.findElement(By.id("currentAddress")).click();
        driver.findElement(By.id("currentAddress")).sendKeys("123PT");
        driver.findElement(By.cssSelector(".css-1pahdxg-control > .css-1hwfws3")).click();
        driver.findElement(By.id("react-select-3-option-1")).click();
        driver.findElement(By.cssSelector(".css-1wa3eu0-placeholder")).click();
        driver.findElement(By.id("react-select-4-option-0")).click();
        driver.findElement(By.id("submit")).click();
        {
            WebElement element = driver.findElement(By.id("submit"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.id("closeLargeModal")).click();
    }
}

